version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "5555:5555"
    env_file:
      - .env.production
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy && pnpm start:prod"   

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mysopwise-db
      POSTGRES_HOST: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
