-- AlterTable
ALTER TABLE "Sop" ADD COLUMN     "affected_departments" TEXT,
ADD COLUMN     "affected_positions" TEXT,
ADD COLUMN     "affected_sites" TEXT,
ADD COLUMN     "approved_locations" TEXT,
ADD COLUMN     "approver_names" TEXT,
ADD COLUMN     "author_names" TEXT,
ADD COLUMN     "cap_checklist_number" TEXT,
ADD COLUMN     "child_document_name" TEXT,
ADD COLUMN     "company_logo_url" TEXT,
ADD COLUMN     "department" TEXT,
ADD COLUMN     "division" TEXT,
ADD COLUMN     "document_number" TEXT,
ADD COLUMN     "effective_date" TIMESTAMP(3),
ADD COLUMN     "iso_checklist_number" TEXT,
ADD COLUMN     "lab_director" TEXT,
ADD COLUMN     "revision_date" TIMESTAMP(3),
ADD COLUMN     "superceded_document_name" TEXT,
ADD COLUMN     "superceded_document_number" TEXT,
ADD COLUMN     "version_number" TEXT;
